package com.example.gullycricket.util

import android.content.Context
import android.graphics.*
import android.net.Uri
import androidx.core.content.FileProvider
import com.example.gullycricket.feature.scoring.MatchState
import java.io.File
import java.io.FileOutputStream

object CanvasExportUtil {
    fun exportMatchSummary(context: Context, state: MatchState): Uri? {
        val width = 1080
        val height = 1920
        val bitmap = Bitmap.createBitmap(width, height, Bitmap.Config.ARGB_8888)
        val canvas = Canvas(bitmap)

        // Background
        val paint = Paint().apply {
            color = Color.parseColor("#121212")
        }
        canvas.drawRect(0f, 0f, width.f, height.f, paint)

        // Header
        paint.color = Color.parseColor("#BB86FC")
        paint.textSize = 80f
        paint.textAlign = Paint.Align.CENTER
        canvas.drawText("GULLY CRICKET SUMMARY", width / 2f, 200f, paint)

        // Teams
        paint.color = Color.WHITE
        paint.textSize = 60f
        canvas.drawText("${state.match?.team1Name} vs ${state.match?.team2Name}", width / 2f, 350f, paint)

        // Score
        paint.textSize = 200f
        paint.color = Color.parseColor("#03DAC6")
        canvas.drawText("${state.totalScore}/${state.totalWickets}", width / 2f, 700f, paint)

        // Overs
        paint.textSize = 100f
        paint.color = Color.WHITE
        canvas.drawText("Overs: ${state.currentOver}.${state.ballsBowledInOver} / ${state.match?.totalOvers}", width / 2f, 850f, paint)

        // Footer
        paint.textSize = 40f
        paint.color = Color.GRAY
        canvas.drawText("Generated by Gully Cricket App", width / 2f, height - 100f, paint)

        // Save to file
        val imagesDir = File(context.cacheDir, "exports")
        imagesDir.mkdirs()
        val file = File(imagesDir, "match_summary_${System.currentTimeMillis()}.png")
        try {
            val out = FileOutputStream(file)
            bitmap.compress(Bitmap.CompressFormat.PNG, 100, out)
            out.flush()
            out.close()
            return FileProvider.getUriForFile(context, "${context.packageName}.provider", file)
        } catch (e: Exception) {
            e.printStackTrace()
            return null
        }
    }
}

private val Int.f get() = this.toFloat()
